name: SSH Deployment

on:
  push:
    branches:
      - ventas

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PEM_FILE }}

    - name: Deploy to EC2
      run: |
        ssh -i C:\Users\madep\Downloads\key-caso-equipo2.pem ec2-user@${{ secrets.REMOTE_HOST }} "echo 'Deployment successful'"
