name: SSH Deployment

on:
  push:
    branches:
      - ventas

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar secretos
      run: |
        echo "PEM_FILE: ${{ secrets.PEM_FILE }}"
        echo "IP_PUBLICA_EC2: ${{ secrets.IP_PUBLICA_EC2 }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KEY_PEM_PC }}

    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.KEY_PEM_PC }} ec2-user@${{ secrets.IP_PUBLICA_EC2 }} 
